apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
        - name: vsftpd
          image: docker.io/fideller/vsftpd:1.0
          ports:
            - containerPort: 20
            - containerPort: 21
          volumeMounts:
            - name: ftp-data
              mountPath: /var/lib/ftp
      volumes:
        - name: ftp-data
          hostPath:
            path: /var/FTP
---
apiVersion: v1
kind: Service
metadata:
  name: vsftpd-service
spec:
  selector:
    app: vsftpd
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: data
      port: 20
      targetPort: 20
  type: ClusterIP
123
